### ISSUE TITLE
Map component

### ISSUE THREAD

**Issue by isedwards** [opencdms/opencdms-app#20]
As a developer, I want the capabilities of #19 to be refactored as a reusable component so that it can be used for the main map view and also used in other places, such as the two column layout (with an image of the station) that is used in the metadata view.

![image.png](https://images.zenhubusercontent.com/5f9160e03cdc92b876df9070/eab7bf3f-0724-473b-b2ea-91e90c61c33e)

**Comment by david-i-berry** [comment]
In progress, see https://app.opencdms.org/#/station/map

**Comment by david-i-berry** [comment]
Can we close this?
